### ISSUE TITLE
In this mode, how to resolve style files?

### ISSUE THREAD

**Issue by kmss-w** [mariusschulz/typescript-webpack-dynamic-import#3]
Thank you for you code, to show me.
But i want to konw how to resolve style files?
My English is not good, I wonder if you can understand me

**Comment by mariusschulz** [comment]
This demo focuses on importing ECMAScript modules only. To learn more about how to use webpack to load CSS files, I suggest you take a look at other projects such as @marharyta's [webpack-boilerplate](https://github.com/marharyta/webpack-boilerplate)!
